# Generated by Django 5.0.1 on 2024-01-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_personne_tasklist_task_voiture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='nom',
            new_name='nom_list',
        ),
    ]
