# Generated by Django 5.0.1 on 2024-01-09 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_nom_task_nom_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='nom',
            new_name='list_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='nom_list',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.task'),
        ),
    ]
