# Generated by Django 5.0.1 on 2024-01-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_task_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task_choice',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
